POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2OWExNTkyMGI4ODFmOWYwMWEzYjcwYjciLCJpYXQiOjE3NzIyMDIzMTh9.f33W4xJD9NF2ZatZRay9H_zrZeoRfUlaYPyF2ia_apE
  
  {
    "title": "The",
    "author": "djtimog",
    "url": "https://localhostwwrw",
    "likes": 3
  }