DELETE http://localhost:3003/api/blogs/69716c73ad6550ba7d254a0a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRtb2ciLCJpZCI6IjY5NzE2NTFlNmNhYjQwNTk1MTE5ZGE5NSIsImlhdCI6MTc2OTAzOTE1NX0.K3H-YPrrTbvFeOKrRY1DSFoFXL3Sz6d42wls5zw4Js0